### ISSUE TITLE
Arrange grid for first artboard to start at x: 0, y:0

### ISSUE THREAD

**Issue by timothywhalin** [romannurik/Sketch-ArtboardTricks#1]
I like to keep the position of my top, left artboard at x:0 and y:0. Ideally, the grid rearrange plugin would either use that logic, or just respect the x/y position of the top left artboard.

**Comment by romannurik** [comment]
Hm what behavior are you seeing now? It should actually set the top left artboard to 0,0 as you describe unless I'm misinterpreting..

**Comment by timothywhalin** [comment]
I have a page with about 18 artboards (6 rows, 4 columns). Before running the script, I had the first artboard at 0,0. After running, the top left artboard is at 629, 474. I've ran the script a couple more times and it still hasn't moved it up to 0,0.

**Comment by timothywhalin** [comment]
I just tested this on a bunch of other files and pages. Some aligned at 0,0 and others moved to random locations within 700x700 of the 0,0 location (never negative, though).

**Comment by romannurik** [comment]
Weird. Will look into it.

_EDIT_: Just reproduced the problem on a local file.

**Comment by romannurik** [comment]
Any chance you could attach an example file that exhibits the broken behavior?

**Comment by romannurik** [comment]
OK, so 0,0 in code doesn't always result in 0,0 in Sketch itself, and I can't seem to find a way to reconcile the two. So for now, I've changed the behavior to just keep the top-left artboard stationary.

See commit e040163eb36adcfcc6bf5fa466d2ff148ff4953a.
