### ISSUE TITLE
Feature request: Allow global custom space setting

### ISSUE THREAD

**Issue by ryanbelisle** [romannurik/Sketch-ArtboardTricks#12]
I'm noticing you have to set custom spacing for each page. Be great if this could be done globally as well.

**Comment by romannurik** [comment]
Good idea!

**Comment by romannurik** [comment]
Fixed in 96b8ef6ae697846be8f16ac4fd04cdd3e7b064d5

**Comment by romannurik** [comment]
Fixed in 1.0.7
