### ISSUE TITLE
Set prefix separator as a setting

### ISSUE THREAD

**Issue by patrickplaggenborg** [romannurik/Sketch-ArtboardTricks#13]
Right now I made a small change to the plugin code to set my separator character to a space.
Also made a small change to the remove prefix code.

It will probably be overwritten with the next Plugin update though :-)

So would be great to allow to set the separator character as a setting.
Or, to set the separator character as a variable in the code, so it allows users to easily change it without breaking it (or forgetting how to).

**Comment by romannurik** [comment]
Good idea!

**Comment by romannurik** [comment]
Started in 96b8ef6ae697846be8f16ac4fd04cdd3e7b064d5
