### ISSUE TITLE
Artboard numbering using `control`+`option`+`command`+`N` is not working

### ISSUE THREAD

**Issue by anthonycarminati** [romannurik/Sketch-ArtboardTricks#14]
It appears the latest update is mislabeling the art board prefixes. My workflow is to hold `control`+`option`+`command` and to hit `R` then `N` so all of the art boards align to a grid and then take on the appropriate numbering prefix. Please see the attached image - thanks!

![screen shot 2017-07-12 at 14 49 27](https://user-images.githubusercontent.com/8963728/28137249-34f33914-6712-11e7-8335-579100598faa.png)

**Comment by romannurik** [comment]
whoa, that's weird. will look into it

**Comment by anthonycarminati** [comment]
awesome - thanks dude
