### ISSUE TITLE
Feature Request: Allow arranging artboards horizontally as well.

### ISSUE THREAD

**Issue by mirkohamann** [romannurik/Sketch-ArtboardTricks#17]
So the user can change/ choose between vertical (image 1) and horizontal (image 2) alignment.
![screenshot1_vertically](https://user-images.githubusercontent.com/14109585/30733767-b47c3e80-9f78-11e7-9f8e-be36110fc39d.png)
![screenshot2_horizontally](https://user-images.githubusercontent.com/14109585/30733768-b47e220e-9f78-11e7-9b27-b1f6dbfdeaf3.png)

**Comment by jamiefang** [comment]
I prefer arranging artboards in rows. It's easier to scroll vertically on trackpad.
