### ISSUE TITLE
Dragging and dropping artboards once in grid does nothing

### ISSUE THREAD

**Issue by startmyquest** [romannurik/Sketch-ArtboardTricks#23]
Hi, I am on Sketch 47.1 and macOS Sierra. The plugin runs the arrange to grid fine, but when I try to drag and drop artboards to new positions, they don't re-arrange.

**Comment by romannurik** [comment]
This is working as intended. You need to rerun the command each time you want to rearrange. I looked into doing it automatically but it wasn't worth it last I checked :-/
