### ISSUE TITLE
Artboard tricks preferences NOT working

### ISSUE THREAD

**Issue by nribak** [romannurik/Sketch-ArtboardTricks#24]
Using Mac El capitan and latest sketch version - the plugin works great but for the preferences. When tapping the option, nothing happens. No popup or anything else. Tried to reinstall plugin automatically and manually but in vain. Please help! can't live with 100,100 default setting forever :(
For more info please contact ystein@shutterfly.com (Gitless)

![image](https://user-images.githubusercontent.com/25723852/34947040-96ba9100-fa11-11e7-8bfd-e720dcc3f67a.png)

**Comment by romannurik** [comment]
Hey there, mind opening the "Console" Mac app, and doing a search for "Sketch", and then trying the Preferences command? You should see some sort of error related to the Artboard Tricks plugin, hopefully you can paste it here :)

**Comment by nribak** [comment]
![pasted image at 2018_01_15 05_19 pm](https://user-images.githubusercontent.com/25723852/35042179-324af554-fb90-11e7-9238-83c0f864c5bf.png)


15/01/2018 17:19:16.736 Sketch[41987]: Exception: TypeError: NSTextField.labelWithString is not a function. (In ‘NSTextField.labelWithString(config.label)’, ‘NSTextField.labelWithString’ is undefined)

15/01/2018 17:19:16.736 Artboard Tricks Preferences (Sketch)[41987]: TypeError: NSTextField.labelWithString is not a function. (In ‘NSTextField.labelWithString(config.label)’, ‘NSTextField.labelWithString’ is undefined)
line: 191
sourceURL: /Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js
column: 52
stack: buildPrefWidget@/Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js:191:52
/Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js:146:39
map@[native code]
buildAlertUi@/Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js:145:42
PreferencesDialog@/Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js:127:22
/Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js:96:24
run@/Users/[user]/Library/Application Support/com.bohemiancoding.sketch3/Plugins/ArtboardTricks.sketchplugin/Contents/Sketch/command-preferences.js:572:17
run@[native code]

**Comment by romannurik** [comment]
Thanks, very helpful! I'll see if there's an alternative API that's available in El Capitan.

**Comment by romannurik** [comment]
Try this version out... does it work for you?

[ArtboardTricks.zip](https://github.com/romannurik/Sketch-ArtboardTricks/files/1639357/ArtboardTricks.zip)

**Comment by romannurik** [comment]
Any luck?

**Comment by nribak** [comment]
![screen shot 2018-01-21 at 09 56 33](https://user-images.githubusercontent.com/25723852/35192043-0803b1c8-fe92-11e7-95da-ea5de28fa7dd.png)

Thanks, It works!!
