### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by stevehobbsPB** [romannurik/Sketch-ArtboardTricks#25]
Rearrange Artboards into Grid function causes Sketch to quit. Have disabled all other plugins and reinstalled.

I'm running version 48.2 on macOS High Sierra version 10.13.2.

Thanks in advance.

**Comment by romannurik** [comment]
Whoa, weird. Mind opening the "Console" Mac app, and doing a search for "Sketch", and then trying the command? You should see some sort of error related to the Artboard Tricks plugin, hopefully you can paste it here :)

**Comment by iyoyak** [comment]
hi there, same issue is happening for me as of this morning (sketch 48.2, ios 10.13.2). Attaching a screenshot of the event in Console.

Thanks for your work on this plugin! 

![screen shot 2018-01-19 at 9 36 50 am](https://user-images.githubusercontent.com/6570095/35163817-d886c4f8-fcfc-11e7-9202-a5bf9b7e7c54.png)

**Comment by romannurik** [comment]
Also for now, feel free to revert back to the previous version (v1.10.2) and see if that fixes it:

https://github.com/romannurik/Sketch-ArtboardTricks/releases/tag/v1.10.2 (the .sketchplugin file is in the "source ZIP")

**Comment by iyoyak** [comment]
Cool, the previous version does not crash. Thanks

**Comment by romannurik** [comment]
Something fishy... might be related to https://github.com/romannurik/Sketch-ArtboardTricks/issues/18.

Can y'all try the very latest version (v1.11.0) of the plugin? You may have been on an older version before.

**Comment by iyoyak** [comment]
You may be right. Don't remember what version I was on before but v1.11.0 works fine now. Thanks!

**Comment by romannurik** [comment]
Ah, great! I think this was the same issue as #18 then.
