### ISSUE TITLE
Latest version needs selection of artboards for rearrangement

### ISSUE THREAD

**Issue by patrickplaggenborg** [romannurik/Sketch-ArtboardTricks#26]
I like how the plugin (version 1.11.1) can now rearrange the selected artboards only.

However, when you want to rearrange all artboards you need some extra steps:
1. Select All (command+A)
2. Select Artboards Containing Selection (thanks to ArtboardTricks)
3. Rearrange

Step 1 + 2 are cumbersome and error prone.

It would be helpful to simply rearrange ALL artboards if there is no selection. Just like before.

Best of both (new and old) worlds?

**Comment by romannurik** [comment]
That's actually how it works, although there needs to be no selection at all (i.e. if you select a layer in an artboard, that still counts as a selection). Are you seeing a different behavior?

**Comment by patrickplaggenborg** [comment]
Ah, you’re right, thanks!

Not sure what happened because I was used to this behaviour. Maybe I did accidentally have a selection which was messing with my rearrangement.

Sorry about that!

**Comment by romannurik** [comment]
No problem! I tend to press the <kbd>Esc</kbd> key to clear selection just in case.

**Comment by patrickplaggenborg** [comment]
Hmm. I do run into the same problem again in my workflow. So something did change. I think I narrowed it down to:

I used to be able to quickly ‘duplicate’ an artboard, by dragging it holding the option key. Then it would overlap with other artboards (because all artboards are neatly arranged and don’t leave space) so I always run the rearrange command immediately after. So while that single artboards was selected, I could run the ‘Rearrange’ command.

Now in the latest update, I have to deselect that single artboard before I rearrange. Otherwise nothing happens.

The only downside of allowing rearrangement with a single artboard selected would be someone could accidentally rearrange everything without wanting to, when just 1 artboard is selected. But that can easily be undone with command+z.

On the positive side, allowing quick rearrangement like before would make the design workflow so much more efficient, because it happens a lot of times.

Would it make sense to still allow rearrangement of ALL layers if just 1 layer is selected?

**Comment by romannurik** [comment]
Yeah that's a potentially good compromise. I think I actually started with
that logic but decided to change it. Let me take another look.

**Comment by romannurik** [comment]
Updated to that behavior btw (select 2+ artboards for a local rearrange)

**Comment by patrickplaggenborg** [comment]
Awesome!
