### ISSUE TITLE
Sketch is crashing with this plugin

### ISSUE THREAD

**Issue by pundeer** [romannurik/Sketch-ArtboardTricks#27]
The newest version of Sketch (49) is crashing each time I try to rearrange artboards into a grid.

**Comment by romannurik** [comment]
Hm, I'm not able to reproduce the crash; could you provide more details? Especially version of the plugin you're using (the latest is 1.11.2), which OS version, and if you see any error messages anywhere

**Comment by romannurik** [comment]
Closed for now please share more details if this is still occurring for you!
