### ISSUE TITLE
Rearrange only selected artboards

### ISSUE THREAD

**Issue by lucasbarcellos** [romannurik/Sketch-ArtboardTricks#3]
Hi!

Not sure that's the way Artboard Tricks was actually designed to behave, but I noticed that running this plugin currently affects all artboards within a page, even if I have only a few of them selected.

I'm assuming it should rearrange all artboards, if none selected, and only the selected ones if there are any. Is that correct?

I'm running Sketch 39.1.

**Comment by romannurik** [comment]
That's a good feature request. Rearranging all artboards is the intended current behavior but I can look into only arranging the selected ones.

**Comment by lucasbarcellos** [comment]
That would be awesome!

**Comment by tpoulos** [comment]
@romannurik are you still looking into this? I'm interested in this feature as well, and I'd love to take a stab at it if you're too busy.

**Comment by romannurik** [comment]
@tpoulos feel free to submit a pull request!

**Comment by romannurik** [comment]
I finally implemented this as part of a0f31c5f2537b1691eb4425dd08651b0e997ca63
