### ISSUE TITLE
Sketch not recognizing plugin

### ISSUE THREAD

**Issue by lazyfives** [romannurik/Sketch-ArtboardTricks#31]
I've uninstalled and reinstalled the plugin several times using various methods (in plugins folder or through "Manage Plugins") and it won't appear in the plugins dropdown menu or in the "Manage Plugins" option. Using Sketch version 51.2 (57519) on OS 10.12.6.

**Comment by romannurik** [comment]
Hmm, I'm really not sure what could be causing this... you don't have this issue with any other plugins? Try installing it with Sketch Runner possibly? Generally downloading the `.zip` and double-clicking the `.sketchplugin` file should work too.

**Comment by lazyfives** [comment]
Hi,

Thanks for the reply. Attaching a couple of screenshots. You'll see I have
the plug-in downloaded into my folder. I also installed Sketch Runner and
it did not find it.

I've installed it both via Sketch Plugin Manager and via download. Neither
has worked. I've also installed your most recent update.

**Comment by romannurik** [comment]
Sorry I don't see any screenshot attachments?

**Comment by lazyfives** [comment]
Didn't go through the email server.

<img width="275" alt="screen shot 2018-09-13 at 12 24 29 pm" src="https://user-images.githubusercontent.com/43049204/45555156-dea01c80-b7ec-11e8-94b6-7848b68df995.png">
<img width="686" alt="screen shot 2018-09-13 at 12 24 04 pm" src="https://user-images.githubusercontent.com/43049204/45555157-dea01c80-b7ec-11e8-92d6-ed946eb7b4d5.png">
<img width="771" alt="screen shot 2018-09-13 at 12 19 55 pm" src="https://user-images.githubusercontent.com/43049204/45555158-df38b300-b7ec-11e8-8459-0898d55c2619.png">

**Comment by romannurik** [comment]
When you expand the "Sketch-ArtboardTricks" folder, does it show a .sketchplugin file there?

**Comment by lazyfives** [comment]
No. All the other plugins do.

I just downloaded it again yesterday, btw.

**Comment by lazyfives** [comment]
Just downloaded it again and no .sketchplugin file is included.

![screen shot 2018-09-14 at 7 39 41 am](https://user-images.githubusercontent.com/43049204/45556969-638d3500-b7f1-11e8-86ea-6db4464c1060.png)

**Comment by romannurik** [comment]
Ah OK, it looks like you're downloading the source code, not the plugin:

- Sketch Plugin Manager may not correctly install plugins where the .sketchplugin isn't in the Git repository directly
- Sketch Runner DOES work, so installing with Sketch Runner should be better. This was a semi recent change they made so you may need to update Runner
- When downloading directly from the GitHub releases page, make sure to use the "To install ..." link rather than Source code or any other link.

**Comment by romannurik** [comment]
For example this should be the right link for 1.11.2:

https://github.com/romannurik/Sketch-ArtboardTricks/releases/download/v1.11.2/ArtboardTricks.sketchplugin.zip

**Comment by lazyfives** [comment]
OK. That did it.

Generally when I've downloaded off GitHub I use "clone or download" button
and choose "download" it gives me a plugin, rather than source code.

One thing to note: I use the plugin Sketch Plugin Manager, and it also
downloads the source code, rather than the plugin, which is what was
causing me confusion as I haven't encountered this with other plugins.

Thank you so much for the help. I'd call this resolved!

Ron

**Comment by romannurik** [comment]
Ah OK :) I'd consider moving to Sketch Runner if you run into more hiccups installing other plugins :)

**Comment by lazyfives** [comment]
Thank you.
