### ISSUE TITLE
Conflicting keyboard shortcut

### ISSUE THREAD

**Issue by AdamSabla** [romannurik/Sketch-ArtboardTricks#32]
The keyboard shortcut `⌘⌃⌥R` is in conflict with another plugin [Rename It](https://rodi01.github.io/RenameIt/). 

I use Rename It way more frequently and now it's overridden with this. I have no problem with clicking through the navigation menu... but I'm so used to that shortcut that I frequently make a mistake that results in reorganising artboards in a page where I don't want it to happen.

Keyboard shortcuts in Sketch live in an anarchy... every plugin can assign their own. That results in conflicts. It would be good to fix this for good.

**Way to fix it**: add checkbox to preferences `disable keyboard shortcuts` to the preferences. Ideal would be to customise it, but I know that's not an easy fix.

PS: Roman, thanks much for writing this plugin. It saved me! There are at least two more other plugins to do similar thing that are unusable. Your is the king! **I'm planning to use this plugin in future frequently, that's why I took the time to write this issue.**

**Comment by romannurik** [comment]
Hey there Adam! Sorry for the late reply. And yeah, I know, keyboard shortcuts in Sketch are painful at the moment :( I'd suggest the workaround of just customizing the shortcut for this plugin through **System Preferences > Keyboard > Shortcuts > App Shortcuts**. Simply create a new app shortcut for **Sketch.app**, for the menu title **Rearrange Artboards into Grid**, and choose whatever other keyboard shortcut you'd prefer. Hope that works for you!
