### ISSUE TITLE
Plugin broken in Sketch 72

### ISSUE THREAD

**Issue by himynameisubik** [romannurik/Sketch-ArtboardTricks#33]
Seems like the newest update of Sketch broke ArtboardTricks. Are you planning on updating it for Sketch 72?
I don't think I can live without ``ctrl cmd option r`` 😨

**Comment by romannurik** [comment]
Oh no! I'll look into this as soon as I can

**Comment by himynameisubik** [comment]
Thanks, much appreciated!

Also fyi: many other Sketch Plugins are broken as well with 72, so it might be a general plugin issue.

**Comment by romannurik** [comment]
Looks like `MSRect.minX` and similar methods are no longer a thing... locally switching to `MSRect.x / y / width / height` works. Will have to investigate a bit more and maybe push a fix.

**Comment by romannurik** [comment]
And yeah, a change like that is certain to break a large swath of plugins.

**Comment by romannurik** [comment]
Fixed in 1.13.0

**Comment by himynameisubik** [comment]
Appreciate it! Works like a charm.
