### ISSUE TITLE
Ignore the symbols artboards

### ISSUE THREAD

**Issue by oscarotero** [romannurik/Sketch-ArtboardTricks#5]
Hi, thanks for this amazing plugin!
The symbols artboards are also arranged and prefixed. I'd love to be able to ignore these artboards.
Thank you!

**Comment by romannurik** [comment]
Do you have your symbols on the same page as your artboards?

**Comment by oscarotero** [comment]
just some non-generic symbols that are used only in the artboards of one page (to avoid repetitions), but make no sense in the rest of the pages.

**Comment by romannurik** [comment]
ah, i gotcha. i'm not sure how frequent of a use case it is to keep some symbols inline w/ artboards and others in another place. could potentially consider a configuration option but am tempted to suggest just forking the code for now (it's pretty easy to filter the things to re-order/re-number to exclude symbols) unless there are a lot more +1's on the request
