### ISSUE TITLE
Rearrange and prefix in the same command.

### ISSUE THREAD

**Issue by brianmoyano2** [romannurik/Sketch-ArtboardTricks#7]
I always run these two commands together, and it's very tedious to do it individually.
Would be good to have a single commands that does it.

**Comment by romannurik** [comment]
Hrm, I'd just fork the plugin… definitely feel like these need to be separate (I personally don't use them together all the time)

**Comment by brianmoyano2** [comment]
When i create new artboards, i like them to follow an order. So, every time i add a new artboard i need to rearange it, to positionate it into the grid, and prefix it because it doesn't follow the naming. It just 'blabla Copy'
Am i using differently than the others?

**Comment by romannurik** [comment]
I personally often just want to re-arrange into a grid without re-numbering. Your usage is pretty standard, but I think it's worth separating these out (just one extra keystroke)

**Comment by sbehrends** [comment]
Maybe we could add another command that executes both sequentially.
_Reorder and Renumber_
Shouldn't be much work to add to the manu. Any idea what the shortcut could be?
