### ISSUE TITLE
Add an icon to help differentiate the plugin from other plugins

### ISSUE THREAD

**Issue by tpoulos** [romannurik/Sketch-ArtboardTricks#8]
Other sketch plugins use an emoji as part of their name to make them more visually distinct and easier to find in the menu. 

![screen shot 2017-02-09 at 12 38 38 pm](https://cloud.githubusercontent.com/assets/2533239/22799217/03284562-eed3-11e6-95fc-1ae17dadb90c.png)

I'd suggest using one of these:

A) 🌟
B) ✨
C) 🎉

Even though there isn't a good emoji counterpart for the word "trick" or "artboard," the word "trick" implies a "tada!" moment, which I think these emoji capture. They're also all bright, and no sketch plugin (so far as I can tell) use them currently.

**Comment by pixelliquid** [comment]
Well you could easily do it yourself on your own installed instance. I personally don't like blinking icons all over the place.
