### ISSUE TITLE
Automatic position of artboard not working

### ISSUE THREAD

**Issue by guzforster** [romannurik/Sketch-ArtboardTricks#9]
On Sketch 43 the auto adjustment of the position for artboards when you drag them is not working. The artboards just stay where you left them, being necessary to execute the "Rearrange command" again...

**Comment by romannurik** [comment]
I'm not sure I fully understand but I think what you're describing is working as intended. You need to manually run the rearrange command to update your artboard positions.

**Comment by guzforster** [comment]
But the in the GIF it shows a drag and drop action where the artboards positions are automatically adjusted. Does that feature exist?

**Comment by romannurik** [comment]
Nope, the keyboard shortcut isn't shown in the GIF, so it's not automatic.
